version: "3.7"

services:
  db:
    image: postgres:12.2
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  api:
    build: .
    depends_on:
      - db
    volumes:
      - .:/books
    ports:
      - '3000:3000'
